### ISSUE TITLE
Error reading SAM file 

### ISSUE THREAD

**Issue by atulkakrana** [TomSkelly/MatchAnnot#2]
Hi Tom,

MatchAnnot is giving me error while reading SAM file:

[DEBUG] 2015-07-06 19:40:05,599 [matchAnnot 60] reading SAM file IsoSeq_Allcells-polished_high_qv.collapsed.rep.sorted.sam
Traceback (most recent call last):
  File "/data1/homes/xyz/tools/matchAnnot/matchAnnot.py", line 540, in <module>
    main()
  File "/data1/homes/xyz/tools/matchAnnot/matchAnnot.py", line 118, in main
    cigar = cs.CigarString(cigarString, start, match.group(1))
  File "/data1/homes/xyz/tools/matchAnnot/CigarString.py", line 79, in **init**
    self.expandCigarString()           # add substitution errors to cigar string
  File "/data1/homes/xyz/tools/matchAnnot/CigarString.py", line 321, in expandCigarString
    raise RuntimeError ('unexpected operation %s in cigar string field %d' % (op, cfIx))
RuntimeError: unexpected operation H in cigar string field 0

Here is what I did - 
1) Mapped FASTA file to genome using GMAP 
2) Sorted SAM file using samtools 
3) Downloaded GTF file from PLANT ENSEMBL 
4) Running matchAnnot like this:

matchAnnot.py --gtf plant.gtf --format alt IsoSeq_Allcells-polished_high_qv.collapsed.rep.sorted.sam > matchedAnnot.out

This is the version I am using - #   20141015.01 - Accept alternate format GTF annotation file.

Any idea how to fix it? Awaiting response.

Atul

**Comment by TomSkelly** [comment]
I never dealt properly with an 'H' field in the cigar string (as produced by GMAP). I've checked in a fix. The unit tests pass. I don't have any GMAP data to try it on. Use with Caution.

--TS
